include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
