name: flutter_memo

packages:
  - app
  - domain
  - data/repository
  - data/datastore
  - model

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    usePubspecOverrides: true
    environment:
      sdk: ">=3.1.0 <4.0.0"
      flutter: ">=3.10.0"
    dependencies:
      flutter:
        sdk: flutter
      collection: ^1.18.0
      flutter_hooks: ^0.20.5
      freezed_annotation: ^2.4.4
      go_router: ^14.2.3
      hooks_riverpod: ^2.5.2
      riverpod_annotation: ^2.3.5
    dev_dependencies:
      flutter_test:
        sdk: flutter
      analyzer: ^6.5.0
      build_runner: ^2.4.12
      custom_lint:
      flutter_lints: ^3.0.1
      freezed: ^2.5.7
      mockito: '^5.4.4'
      riverpod_generator: ^2.4.3
      riverpod_lint: ^2.3.13

scripts:
  prepare: melos bs && melos run build_runner:all

  outdated:
    run: |
      flutter pub outdated --show-all --transitive
    exec:
      failFast: true
    packageFilters:
      scope: "flutter_memo"

# ---------------------------------- run app -----------------------------------

  app:
    run: |
      melos analyze && 
      flutter run
    exec:
      failFast: true
    packageFilters:
      scope: "flutter_memo"

# ------------------------------ run build_runner ------------------------------
 
  build_runner:all:
    run: |
      melos run build_runner:app && 
      melos run build_runner:domain && 
      melos run build_runner:data:repository && 
      melos run build_runner:data:datastore && 
      melos run build_runner:model

  build_runner:app:
    run: |
      dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
    packageFilters:
      scope: "flutter_memo"

  build_runner:domain:
    run:
      dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
    packageFilters:
      scope: "domain"

  build_runner:data:datastore:
    run: |
      dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
    packageFilters:
      scope: "datastore"

  build_runner:data:repository:
    run: |
      dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
    packageFilters:
      scope: "repository"

  build_runner:model:
    run: |
      dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
    packageFilters:
      scope: "model"

# ------------------------------------ Test ------------------------------------

  test:all:
    run: |
      melos run test:data:repository && 
      melos run test:data:datastore

  test:app:
    run:
      flutter test
    exec:
      failFast: true
    packageFilters:
      scope: "flutter_memo"

  test:model:
    run: |
      flutter test
    exec:
      failFast: true
    packageFilters:
      scope: "model"

  test:data:repository:
    run: |
      flutter test
    exec:
      failFast: true
    packageFilters:
      scope: "repository"

  test:data:datastore:
    run:
      flutter test
    exec:
      failFast: true
    packageFilters:
      scope: "datastore"

# -------------------------------- dependencies --------------------------------

  deps:app:
    run: flutter pub deps -C app -s compact

  deps:domain:
    run: flutter pub deps -C domain -s compact

  deps:model:
    run: flutter pub deps -C model -s compact

  deps:data:repository:
    run: flutter pub deps -C data/repository -s compact

  deps:data:datastore:
    run: flutter pub deps -C data/datastore -s compact
