targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/note/{{}}.dart': 'lib/note/generated/{{}}.g.dart'
      mockito:mockBuilder:
        options:
          build_extensions:
            '^test/{{}}.dart': 'test/mocks/{{}}.mocks.dart'
